### ISSUE TITLE
Elements and Sets

### ISSUE THREAD

**Issue by LOZORD** [Jam3/math-as-code#13]
I think it might be more mathematically "correct" to use Sets instead of Arrays for [Elements](https://github.com/Jam3/math-as-code/blob/master/README.md#element) ("In"/"Not In"). Most of the time, mathematicians make the assumption that they are working on sets (uniqueness, abstract ordering) instead of lists. I know it depends on usage, especially with respect to game and graphics dev, but I think the ES6/Harmony API for Set is pretty nifty!

**Comment by mattdesl** [comment]
:+1: Good call, thanks. I've left the ES5 for reference.
