### ISSUE TITLE
Why are you using images instead of unicode?

### ISSUE THREAD

**Issue by StoneCypher** [Jam3/math-as-code#15]

**Comment by mattdesl** [comment]
see discussion in #2 and #4

**Comment by StoneCypher** [comment]
I submitted a single PR before this answer came in.

I will wait for further discussion before continuing.  However most math on the web eventually moves to Unicode, and I would like to try to save you the effort of converting later.

This Should Be Unicode &trade;.

**Comment by mattdesl** [comment]
SVG is the plan going forward since it renders crisply and most closely resembles the literature this guide is intending to "demystify." :smile: 

Unicode will continue to be used in some places, though (as it is now).

**Comment by StoneCypher** [comment]
svg is a good plan

i confess i wouldn't want the work load, but if you're willing to do it, more power to you

doesn't seem like it resolves the characterset support problem you raised else-ticket though (unless you intend to render letters as polygons?)

**Comment by mattdesl** [comment]
images have been replaced with SVG. closing due to #28
