### ISSUE TITLE
Sigma n or i

### ISSUE THREAD

**Issue by elektrowolle** [Jam3/math-as-code#19]
at the Sigma part:

```js
var sum = 0
for (var i = 1; i <= 100; i++) {
  sum += i
}
```

```js
var n = 100 // upper bound
var sum = (n * (n + 1)) / 2
```

shouldn't n be i?

**Comment by mattdesl** [comment]
I chose the variable name `n` (for upper bound) to distinguish it from `i=1` (index and lower bound).

Perhaps the "optimization tip" is a bit confusing, since it is not coming from any listed equations?

**Comment by elektrowolle** [comment]
This makes perfectly sense. I confused my self with not seeing the literal n in the formula. But of course it's there.
