### ISSUE TITLE
prime symbol

### ISSUE THREAD

**Issue by nickdesaulniers** [Jam3/math-as-code#5]
primes represent the next value, for example:

A' = A * MVP
can be thought of as
A *= MVP

The single apostrophe is sometimes referred to as prime. "Matrix A prime is the result of matrix A times matrix MVP"

**Comment by mattdesl** [comment]
For review: https://github.com/Jam3/math-as-code/tree/feature/derivatives-integrals#prime

**Comment by yoshuawuyts** [comment]
lgtm! Very comprehensible, though I have prior knowledge about derivatives.

**Comment by nickdesaulniers** [comment]
great work Matt

**Comment by mattdesl** [comment]
merged the prime / function in
