### ISSUE TITLE
Ambiguity in the variable definition section

### ISSUE THREAD

**Issue by nighthawk702** [Jam3/math-as-code#8]
I think that it should be noted that the JS code isn't equivalent, as in math the '=' sign denotes an alias when used as presented.

I saw that you noted that 'x' is just another name, but further clarification would be beneficial in my opinion.

Hope this helps.

PS: Love your effort. I think it will be useful for a lot of people. If I get some free time, expect some pull requests from me. Keep up the good work.

**Comment by mattdesl** [comment]
Thanks, hope this is better. :smile:

> In code, we can use `=` to *define* our variables and provide aliases.

> ```js
var x = 2 * k * j
var k = x / (2 * j)
var j = x / (2 * k)
```

PRs would be great! :+1:

**Comment by mattdesl** [comment]
Update: I separated the three to make it clear the code examples are independent.

**Comment by nighthawk702** [comment]
Looks good.
